In [2]:
import numpy as np

In [5]:
my_list = [1,2,3,4,5,6]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5 6]


In [7]:
my_array = np.array([1,2,3,4,5,6])

In [9]:
prices = [30,25,50,100,85]
new_prices = [price-5 for price in prices]
print(new_prices)

[25, 20, 45, 95, 80]


In [15]:
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])
print(test_1,test_2,test_3)
test_3_fixed = [score + 2 for score in test_3]
print(test_3_fixed)

[92 94 88 91 87] [ 79 100  86  93  91] [87 85 72 90 92]
[89, 87, 74, 92, 94]


In [20]:
total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

[260 281 248 276 272]


In [21]:
final_grade = total_grade / 3
print(final_grade)

[86.66666667 93.66666667 82.66666667 92.         90.66666667]


In [23]:
jeremy_test_2 = test_2[3]
print(jeremy_test_2)

93


In [30]:
manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

[94 88]


In [33]:
student_scores = np.array([test_1,test_2,test_3])
print(student_scores)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]


In [36]:
student_scores[2,0]

87

In [40]:
student_scores[:,4] # ':' = 모두 선택

array([87, 91, 92])

In [42]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

[ True False False False False False  True  True  True  True]


In [44]:
selected = a[a > 5]
print(selected)

[10  9  8  9  7]


In [46]:
selected = a[(a > 5) | (a < 3)]
print(selected)

[10  2  2  9  8  9  7]


In [62]:
porridge = np.array([79,65,50,63,56,90,85,98,79,51])
print(porridge)

[79 65 50 63 56 90 85 98 79 51]


In [63]:
cold = porridge[porridge < 60]
print(cold)

[50 56 51]


In [64]:
hot = porridge[porridge > 80]
print(hot)

[90 85 98]


In [65]:
just_right = porridge[(porridge > 60) | (porridge < 80)]
print(just_right)

[79 65 50 63 56 90 85 98 79 51]


In [67]:
 np.random.randint(100, size=(3, 5))

array([[16, 38, 26, 33, 71],
       [17, 22, 63, 41, 13],
       [69, 30, 97, 25, 60]])

In [72]:
arr = np.arange(10)
arr[3:7]# start = 3, stop = 7(stop-1 원소까지 선택)
arr[:5]#처음부터
arr[5:]# 끝까지
arr[2:8:2]

array([2, 4, 6])

In [77]:
arr = np.random.randint(10, size=(6,8))
arr[3:5,4:7]

array([[5, 6, 2],
       [7, 9, 4]])

In [79]:
vec = np.arange(10)

arr = vec.reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
arr_new = arr[np.newaxis, :]
arr_new

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [84]:
arr_new = arr[:, np.newaxis]
arr_new

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [92]:
arr_1 = np.arange(10)
arr_2 = np.arange(10,20)
arr_3 = np.arange(20,30)
print(arr_1,arr_2,arr_3)

arr_total = np.hstack([arr_1,arr_2,arr_3])
print(arr_total)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19] [20 21 22 23 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [5]:
a = np.arange(5)
print(a)


[0 1 2 3 4]


In [9]:
x = np.random.randint(10, size=(10))
print(x)

[1 0 7 5 2 0 0 6 8 3]


In [11]:
ind = [2,4,6]
x[ind]

array([7, 2, 0])